---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: phpipam-backup-db
  namespace: phpipam-system

spec:
  storageClassName: gp1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
