---
apiVersion: v1
kind: Service
metadata:
  name: svc-haproxy-stats
  namespace: ingress-controller
spec:
  ports:
  - name: http
    port: 1936
    targetPort: 1936
    protocol: TCP

  selector:
    run: haproxy-ingress
