---
apiVersion: v1
kind: Service
metadata:
  name: svc-haproxy-stats
  namespace: haproxy-ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 1936
    protocol: TCP

  selector:
    app: haproxy-ingress
